from PySide6 import QtGui, QtWidgets


def build_dashboard_tab(window, tabs: QtWidgets.QTabWidget):
    dash = QtWidgets.QWidget()
    dash_layout = QtWidgets.QVBoxLayout(dash)

    window.status_label = QtWidgets.QLabel("Status: unknown")
    window.status_label.setObjectName("statusLabel")
    dash_layout.addWidget(window.status_label)

    monitor_box = QtWidgets.QGroupBox("Bot Monitor")
    monitor_grid = QtWidgets.QGridLayout(monitor_box)
    monitor_grid.setHorizontalSpacing(12)
    monitor_grid.setVerticalSpacing(6)

    window.mon_ready = QtWidgets.QLabel("—")
    window.mon_user = QtWidgets.QLabel("—")
    window.mon_ping = QtWidgets.QLabel("—")
    window.mon_uptime = QtWidgets.QLabel("—")
    window.mon_cpu = QtWidgets.QLabel("—")
    window.mon_mem = QtWidgets.QLabel("—")
    window.mon_cogs = QtWidgets.QLabel("—")

    monitor_grid.addWidget(QtWidgets.QLabel("Ready:"), 0, 0)
    monitor_grid.addWidget(window.mon_ready, 0, 1)
    monitor_grid.addWidget(QtWidgets.QLabel("User:"), 0, 2)
    monitor_grid.addWidget(window.mon_user, 0, 3)
    monitor_grid.addWidget(QtWidgets.QLabel("Ping:"), 1, 0)
    monitor_grid.addWidget(window.mon_ping, 1, 1)
    monitor_grid.addWidget(QtWidgets.QLabel("Uptime:"), 1, 2)
    monitor_grid.addWidget(window.mon_uptime, 1, 3)
    monitor_grid.addWidget(QtWidgets.QLabel("CPU:"), 2, 0)
    monitor_grid.addWidget(window.mon_cpu, 2, 1)
    monitor_grid.addWidget(QtWidgets.QLabel("Memory:"), 2, 2)
    monitor_grid.addWidget(window.mon_mem, 2, 3)
    monitor_grid.addWidget(QtWidgets.QLabel("Cogs:"), 3, 0)
    monitor_grid.addWidget(window.mon_cogs, 3, 1)

    console_box = QtWidgets.QGroupBox("Live Console")
    console_layout = QtWidgets.QVBoxLayout(console_box)
    window.dash_console = QtWidgets.QPlainTextEdit()
    window.dash_console.setReadOnly(True)
    window.dash_console.setMaximumBlockCount(1200)
    window.dash_console.setPlaceholderText("Start the app via start_all.bat/start_all.py to see terminal output here.")
    console_layout.addWidget(window.dash_console)

    btn_row = QtWidgets.QHBoxLayout()
    window.refresh_btn = QtWidgets.QPushButton("Refresh Status")
    window.reload_btn = QtWidgets.QPushButton("Reload Cogs")
    window.shutdown_btn = QtWidgets.QPushButton("Shutdown Bot")
    window.restart_btn = QtWidgets.QPushButton("Restart Bot & UI")
    window.setup_wizard_btn = QtWidgets.QPushButton("Setup Wizard")

    for w in (window.refresh_btn, window.reload_btn, window.shutdown_btn):
        btn_row.addWidget(w)
    btn_row.addWidget(window.restart_btn)

    tools_box = QtWidgets.QGroupBox("Tools")
    tools_layout = QtWidgets.QHBoxLayout(tools_box)
    tools_layout.addLayout(btn_row)
    tools_layout.addStretch()
    dash_layout.addWidget(tools_box)

    test_box = QtWidgets.QGroupBox("Event Tester")
    test_layout = QtWidgets.QHBoxLayout(test_box)
    window.event_test_combo = QtWidgets.QComboBox()
    window.event_test_combo.addItem("Ping (testping)", "testping")
    window.event_test_combo.addItem("Rank (testrank)", "testrank")
    window.event_test_combo.addItem("Count (testcount)", "testcount")
    window.event_test_combo.addItem("Birthday (testbirthday)", "testbirthday")
    window.event_test_combo.addItem("Poll (testpoll)", "testpoll")
    window.event_test_combo.addItem("Ticket Panel (testticketpanel)", "testticketpanel")
    window.event_test_combo.addItem("Music (testmusic)", "testmusic")
    window.event_test_combo.addItem("Say (testsay)", "testsay")
    window.event_test_combo.addItem("Level (testlevel)", "testlevel")
    window.event_test_combo.addItem("Achievement (testachievement)", "testachievement")
    window.event_test_combo.addItem("Log (testlog)", "testlog")
    window.event_test_channel_id = QtWidgets.QLineEdit()
    window.event_test_channel_id.setPlaceholderText("Channel ID (optional)")
    window.event_test_channel_id.setMaximumWidth(220)
    window.run_event_test_btn = QtWidgets.QPushButton("Run Test")
    test_layout.addWidget(QtWidgets.QLabel("Admin Test:"))
    test_layout.addWidget(window.event_test_combo)
    test_layout.addWidget(QtWidgets.QLabel("Channel ID:"))
    test_layout.addWidget(window.event_test_channel_id)
    test_layout.addWidget(window.run_event_test_btn)
    test_layout.addStretch()
    dash_layout.addWidget(test_box)

    safe_box = QtWidgets.QGroupBox("Safe Mode")
    safe_layout = QtWidgets.QHBoxLayout(safe_box)
    window.safe_read_only_chk = QtWidgets.QCheckBox("Nur lesen")
    window.safe_debug_logging_chk = QtWidgets.QCheckBox("Debug logging an")
    window.safe_auto_reload_off_chk = QtWidgets.QCheckBox("Auto reload aus")
    safe_layout.addWidget(window.safe_read_only_chk)
    safe_layout.addWidget(window.safe_debug_logging_chk)
    safe_layout.addWidget(window.safe_auto_reload_off_chk)
    safe_layout.addStretch()
    dash_layout.addWidget(safe_box)

    dash_layout.addWidget(monitor_box)
    dash_layout.addWidget(console_box)

    dash_layout.addStretch()

    help_box = QtWidgets.QGroupBox("Help")
    help_layout = QtWidgets.QHBoxLayout(help_box)
    window.tutorial_btn = QtWidgets.QPushButton("Bot Tutorial (*help)")
    window.commands_btn = QtWidgets.QPushButton("Commands (*admin_help)")
    window.tutorial_btn.setToolTip("Discord help: *help (aliases: *tutorial, *hilfe)")
    window.commands_btn.setToolTip("Admin help: *admin_help (aliases: *adminhelp, *ahelp)")
    help_layout.addWidget(window.setup_wizard_btn)
    help_layout.addWidget(window.tutorial_btn)
    help_layout.addWidget(window.commands_btn)
    help_layout.addStretch()
    dash_layout.addWidget(help_box)

    window.refresh_btn.clicked.connect(window.on_refresh)
    window.reload_btn.clicked.connect(window.on_reload)
    window.tutorial_btn.clicked.connect(window.on_open_bot_tutorial)
    window.commands_btn.clicked.connect(window.on_open_commands_guide)
    window.shutdown_btn.clicked.connect(window.on_shutdown)
    window.restart_btn.clicked.connect(window.on_restart_and_restart_ui)
    window.setup_wizard_btn.clicked.connect(window.on_open_setup_wizard)
    window.run_event_test_btn.clicked.connect(window.on_run_admin_test_command)
    window.event_test_channel_id.editingFinished.connect(window.on_event_test_channel_changed)
    window.safe_read_only_chk.stateChanged.connect(window.on_safe_mode_flags_changed)
    window.safe_debug_logging_chk.stateChanged.connect(window.on_safe_mode_flags_changed)
    window.safe_auto_reload_off_chk.stateChanged.connect(window.on_safe_mode_flags_changed)

    tabs.addTab(dash, "Dashboard")


def build_logs_tab(window, tabs: QtWidgets.QTabWidget):
    logs = QtWidgets.QWidget()
    logs_layout = QtWidgets.QVBoxLayout(logs)
    top_row = QtWidgets.QHBoxLayout()
    window.choose_log_btn = QtWidgets.QPushButton("Choose Log...")
    window.clear_log_btn = QtWidgets.QPushButton("Clear")
    top_row.addWidget(window.choose_log_btn)
    top_row.addWidget(window.clear_log_btn)
    top_row.addStretch()
    logs_layout.addLayout(top_row)

    window.log_text = QtWidgets.QPlainTextEdit()
    window.log_text.setReadOnly(True)
    try:
        window.log_text.setFont(QtGui.QFont("Consolas", 10))
    except Exception:
        pass
    logs_layout.addWidget(window.log_text)

    window.choose_log_btn.clicked.connect(window._choose_log_file)
    window.clear_log_btn.clicked.connect(lambda: window.log_text.clear())
    tabs.addTab(logs, "Logs")


def build_configs_tab(window, tabs: QtWidgets.QTabWidget, config_editor_cls):
    window.cfg_editor = config_editor_cls(window)
    tabs.addTab(window.cfg_editor, "Configs")


def build_welcome_and_rank_tabs(window, tabs: QtWidgets.QTabWidget, QtCore):
    def _section_label(text: str) -> QtWidgets.QLabel:
        label = QtWidgets.QLabel(text)
        label.setObjectName("sectionLabel")
        return label

    preview_w = QtWidgets.QWidget()
    pv_layout = QtWidgets.QVBoxLayout(preview_w)
    pv_layout.setContentsMargins(8, 8, 10, 8)
    pv_layout.setSpacing(10)

    pv_top = QtWidgets.QHBoxLayout()
    pv_top.setSpacing(12)
    pv_left = QtWidgets.QVBoxLayout()
    pv_lbl_preview = QtWidgets.QLabel("Preview")
    pv_lbl_preview.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
    pv_lbl_preview.setStyleSheet("font-weight:700; font-size:14px; margin-bottom:6px;")
    pv_left.addWidget(pv_lbl_preview)
    window.pv_banner = QtWidgets.QLabel()
    window.pv_banner.setFixedSize(520, 180)
    window.pv_banner.setScaledContents(False)
    pv_left.addWidget(window.pv_banner)
    pv_left.addStretch()
    pv_top.addLayout(pv_left, 0)

    pv_form = QtWidgets.QFormLayout()
    pv_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
    pv_form.setFormAlignment(QtCore.Qt.AlignTop | QtCore.Qt.AlignLeft)
    pv_form.setLabelAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
    pv_form.setHorizontalSpacing(10)
    pv_form.setVerticalSpacing(8)
    pv_form.setContentsMargins(0, 0, 18, 0)

    pv_form.addRow(_section_label("General"))
    window.pv_name = QtWidgets.QLineEdit()
    window.pv_banner_path = QtWidgets.QLineEdit()
    window.pv_banner_browse = QtWidgets.QPushButton("Choose...")
    h = QtWidgets.QHBoxLayout()
    h.addWidget(window.pv_banner_path)
    h.addWidget(window.pv_banner_browse)
    pv_form.addRow("Example name:", window.pv_name)
    pv_form.addRow("Banner image:", h)
    window.pv_message = QtWidgets.QPlainTextEdit()
    window.pv_message.setMinimumHeight(150)
    window.pv_message.setMaximumHeight(220)
    window.pv_message.setPlaceholderText("Welcome message template. Use {mention} for mention.")
    pv_form.addRow("Message:", window.pv_message)

    ph_widget = QtWidgets.QWidget()
    ph_grid = QtWidgets.QGridLayout(ph_widget)
    ph_grid.setContentsMargins(0, 0, 0, 0)
    ph_grid.setHorizontalSpacing(8)
    ph_grid.setVerticalSpacing(8)
    window.ph_mention = QtWidgets.QPushButton("{mention}")
    window.ph_rules = QtWidgets.QPushButton("{rules_channel}")
    window.ph_verify = QtWidgets.QPushButton("{verify_channel}")
    window.ph_about = QtWidgets.QPushButton("{aboutme_channel}")
    for _btn in (window.ph_mention, window.ph_rules, window.ph_verify, window.ph_about):
        try:
            _btn.setMinimumHeight(34)
        except Exception:
            pass
    ph_grid.addWidget(window.ph_mention, 0, 0)
    ph_grid.addWidget(window.ph_rules, 0, 1)
    ph_grid.addWidget(window.ph_verify, 0, 2)
    ph_grid.addWidget(window.ph_about, 0, 3)
    pv_form.addRow("Placeholders:", ph_widget)

    window.pv_emoji_picker_btn = QtWidgets.QPushButton("Server Emoji Picker...")
    pv_form.addRow("Server emojis:", window.pv_emoji_picker_btn)

    pv_form.addRow(_section_label("Background"))
    window.pv_bg_mode = QtWidgets.QComboBox()
    window.pv_bg_mode.addItem("Fill (cover)", "cover")
    window.pv_bg_mode.addItem("Fit (contain)", "contain")
    window.pv_bg_mode.addItem("Stretch", "stretch")
    pv_form.addRow("Background mode:", window.pv_bg_mode)

    window.pv_bg_zoom = QtWidgets.QSpinBox()
    window.pv_bg_zoom.setRange(10, 400)
    window.pv_bg_zoom.setValue(100)
    window.pv_bg_zoom.setSuffix(" %")
    window.pv_bg_zoom.setFixedWidth(120)
    pv_form.addRow("Background zoom:", window.pv_bg_zoom)

    bg_pos_row = QtWidgets.QHBoxLayout()
    window.pv_bg_x = QtWidgets.QSpinBox()
    window.pv_bg_x.setRange(-4000, 4000)
    window.pv_bg_x.setSingleStep(10)
    window.pv_bg_x.setFixedWidth(110)
    window.pv_bg_y = QtWidgets.QSpinBox()
    window.pv_bg_y.setRange(-4000, 4000)
    window.pv_bg_y.setSingleStep(10)
    window.pv_bg_y.setFixedWidth(110)
    bg_pos_row.addWidget(QtWidgets.QLabel("X"))
    bg_pos_row.addWidget(window.pv_bg_x)
    bg_pos_row.addSpacing(10)
    bg_pos_row.addWidget(QtWidgets.QLabel("Y"))
    bg_pos_row.addWidget(window.pv_bg_y)
    bg_pos_row.addStretch()
    pv_form.addRow("Background offset:", bg_pos_row)

    pv_form.addRow(_section_label("Typography"))
    window.pv_title = QtWidgets.QLineEdit()
    window.pv_title.setPlaceholderText("WELCOME")
    pv_form.addRow("Banner title:", window.pv_title)

    window.pv_title_font = QtWidgets.QComboBox()
    window.pv_title_font.setEditable(True)
    window.pv_title_font.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
    pv_form.addRow("Title font:", window.pv_title_font)

    window.pv_user_font = QtWidgets.QComboBox()
    window.pv_user_font.setEditable(True)
    window.pv_user_font.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
    pv_form.addRow("Username font:", window.pv_user_font)

    window.pv_title_size = QtWidgets.QSpinBox()
    window.pv_title_size.setRange(8, 400)
    window.pv_title_size.setValue(140)
    window.pv_title_size.setFixedWidth(120)
    pv_form.addRow("Title size:", window.pv_title_size)

    window.pv_user_size = QtWidgets.QSpinBox()
    window.pv_user_size.setRange(8, 300)
    window.pv_user_size.setValue(64)
    window.pv_user_size.setFixedWidth(120)
    pv_form.addRow("Username size:", window.pv_user_size)

    window.pv_title_color = QtWidgets.QLineEdit()
    window.pv_title_color.setPlaceholderText("#FFFFFF")
    window.pv_title_color_pick = QtWidgets.QPushButton("Pick...")
    window.pv_title_color_pick.setFixedWidth(72)
    title_color_row = QtWidgets.QHBoxLayout()
    title_color_row.addWidget(window.pv_title_color, 1)
    title_color_row.addWidget(window.pv_title_color_pick, 0)
    pv_form.addRow("Title color:", title_color_row)

    window.pv_user_color = QtWidgets.QLineEdit()
    window.pv_user_color.setPlaceholderText("#E6E6E6")
    window.pv_user_color_pick = QtWidgets.QPushButton("Pick...")
    window.pv_user_color_pick.setFixedWidth(72)
    user_color_row = QtWidgets.QHBoxLayout()
    user_color_row.addWidget(window.pv_user_color, 1)
    user_color_row.addWidget(window.pv_user_color_pick, 0)
    pv_form.addRow("Username color:", user_color_row)

    pv_form.addRow(_section_label("Position"))
    title_pos_row = QtWidgets.QHBoxLayout()
    window.pv_title_x = QtWidgets.QSpinBox()
    window.pv_title_x.setRange(-2000, 2000)
    window.pv_title_x.setSingleStep(5)
    window.pv_title_x.setFixedWidth(110)
    window.pv_title_y = QtWidgets.QSpinBox()
    window.pv_title_y.setRange(-2000, 2000)
    window.pv_title_y.setSingleStep(5)
    window.pv_title_y.setFixedWidth(110)
    title_pos_row.addWidget(QtWidgets.QLabel("X"))
    title_pos_row.addWidget(window.pv_title_x)
    title_pos_row.addSpacing(10)
    title_pos_row.addWidget(QtWidgets.QLabel("Y"))
    title_pos_row.addWidget(window.pv_title_y)
    title_pos_row.addStretch()
    pv_form.addRow("Title offset:", title_pos_row)

    user_pos_row = QtWidgets.QHBoxLayout()
    window.pv_user_x = QtWidgets.QSpinBox()
    window.pv_user_x.setRange(-2000, 2000)
    window.pv_user_x.setSingleStep(5)
    window.pv_user_x.setFixedWidth(110)
    window.pv_user_y = QtWidgets.QSpinBox()
    window.pv_user_y.setRange(-2000, 2000)
    window.pv_user_y.setSingleStep(5)
    window.pv_user_y.setFixedWidth(110)
    user_pos_row.addWidget(QtWidgets.QLabel("X"))
    user_pos_row.addWidget(window.pv_user_x)
    user_pos_row.addSpacing(10)
    user_pos_row.addWidget(QtWidgets.QLabel("Y"))
    user_pos_row.addWidget(window.pv_user_y)
    user_pos_row.addStretch()
    pv_form.addRow("Username offset:", user_pos_row)

    text_pos_row = QtWidgets.QHBoxLayout()
    window.pv_text_x = QtWidgets.QSpinBox()
    window.pv_text_x.setRange(-2000, 2000)
    window.pv_text_x.setSingleStep(5)
    window.pv_text_x.setFixedWidth(110)
    window.pv_text_y = QtWidgets.QSpinBox()
    window.pv_text_y.setRange(-2000, 2000)
    window.pv_text_y.setSingleStep(5)
    window.pv_text_y.setFixedWidth(110)
    text_pos_row.addWidget(QtWidgets.QLabel("X"))
    text_pos_row.addWidget(window.pv_text_x)
    text_pos_row.addSpacing(10)
    text_pos_row.addWidget(QtWidgets.QLabel("Y"))
    text_pos_row.addWidget(window.pv_text_y)
    text_pos_row.addStretch()
    pv_form.addRow("Text offset:", text_pos_row)

    pos_row = QtWidgets.QHBoxLayout()
    window.pv_avatar_x = QtWidgets.QSpinBox()
    window.pv_avatar_x.setRange(-2000, 2000)
    window.pv_avatar_x.setSingleStep(5)
    window.pv_avatar_x.setFixedWidth(110)
    window.pv_avatar_y = QtWidgets.QSpinBox()
    window.pv_avatar_y.setRange(-2000, 2000)
    window.pv_avatar_y.setSingleStep(5)
    window.pv_avatar_y.setFixedWidth(110)
    pos_row.addWidget(QtWidgets.QLabel("X"))
    pos_row.addWidget(window.pv_avatar_x)
    pos_row.addSpacing(10)
    pos_row.addWidget(QtWidgets.QLabel("Y"))
    pos_row.addWidget(window.pv_avatar_y)
    pos_row.addStretch()
    pv_form.addRow("Avatar offset:", pos_row)

    window.ph_mention.clicked.connect(lambda: window._insert_placeholder('{mention}'))
    window.ph_rules.clicked.connect(lambda: window._insert_placeholder('{rules_channel}'))
    window.ph_verify.clicked.connect(lambda: window._insert_placeholder('{verify_channel}'))
    window.ph_about.clicked.connect(lambda: window._insert_placeholder('{aboutme_channel}'))

    pv_controls_w = QtWidgets.QWidget()
    pv_controls_w.setLayout(pv_form)
    pv_scroll = QtWidgets.QScrollArea()
    pv_scroll.setWidgetResizable(True)
    pv_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
    pv_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
    pv_scroll.setContentsMargins(0, 0, 10, 0)
    pv_scroll.setWidget(pv_controls_w)
    pv_top.addWidget(pv_scroll, 1)
    pv_layout.addLayout(pv_top)

    pv_row = QtWidgets.QHBoxLayout()
    window.pv_save = QtWidgets.QPushButton("Save")
    window.pv_save_reload = QtWidgets.QPushButton("Save + Reload")
    window.pv_refresh = QtWidgets.QPushButton("Refresh Preview")
    for _btn in (window.pv_refresh, window.pv_save, window.pv_save_reload):
        try:
            _btn.setMinimumWidth(_btn.sizeHint().width() + 18)
            _btn.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        except Exception:
            pass
    pv_row.addStretch()
    pv_row.addWidget(window.pv_refresh)
    pv_row.addWidget(window.pv_save)
    pv_row.addWidget(window.pv_save_reload)
    pv_layout.addLayout(pv_row)

    tabs.addTab(preview_w, "Welcome")

    rank_w = QtWidgets.QWidget()
    rank_layout = QtWidgets.QVBoxLayout(rank_w)
    rank_layout.setContentsMargins(8, 8, 10, 8)
    rank_layout.setSpacing(10)

    rk_main = QtWidgets.QHBoxLayout()
    rk_main.setSpacing(12)

    rk_left = QtWidgets.QVBoxLayout()
    lbl_preview = QtWidgets.QLabel("Preview")
    lbl_preview.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
    lbl_preview.setStyleSheet("font-weight:700; font-size:14px; margin-bottom:6px;")
    rk_left.addWidget(lbl_preview)
    window.rk_image = QtWidgets.QLabel()
    window.rk_image.setFixedSize(520, 180)
    window.rk_image.setScaledContents(False)
    rk_left.addWidget(window.rk_image)
    rk_left.addStretch()

    rk_right = QtWidgets.QVBoxLayout()
    rk_right.setSpacing(10)
    rk_right.setContentsMargins(0, 0, 6, 0)
    rk_controls_w = QtWidgets.QWidget()
    rk_controls_w.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
    rk_controls_layout = QtWidgets.QVBoxLayout(rk_controls_w)
    rk_controls_layout.setContentsMargins(0, 0, 10, 0)
    rk_controls_layout.setSpacing(8)
    rk_form = QtWidgets.QFormLayout()
    rk_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
    rk_form.setFormAlignment(QtCore.Qt.AlignTop | QtCore.Qt.AlignLeft)
    rk_form.setLabelAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
    rk_form.setHorizontalSpacing(10)
    rk_form.setVerticalSpacing(8)
    rk_form.setContentsMargins(0, 0, 18, 0)
    rk_form.addRow(_section_label("General"))
    window.rk_name = QtWidgets.QLineEdit()
    window.rk_bg_path = QtWidgets.QLineEdit()
    window.rk_bg_browse = QtWidgets.QPushButton("Choose...")
    hbg = QtWidgets.QHBoxLayout()
    hbg.addWidget(window.rk_bg_path)
    hbg.addWidget(window.rk_bg_browse)
    rk_form.addRow("Example name:", window.rk_name)
    rk_form.addRow("Background PNG:", hbg)
    rk_form.addRow(_section_label("Background"))
    window.rk_bg_mode = QtWidgets.QComboBox()
    window.rk_bg_mode.addItem("Fill (cover)", "cover")
    window.rk_bg_mode.addItem("Fit (contain)", "contain")
    window.rk_bg_mode.addItem("Stretch", "stretch")
    rk_form.addRow("Background mode:", window.rk_bg_mode)

    window.rk_bg_zoom = QtWidgets.QSpinBox()
    window.rk_bg_zoom.setRange(10, 400)
    window.rk_bg_zoom.setValue(100)
    window.rk_bg_zoom.setSuffix(" %")
    window.rk_bg_zoom.setFixedWidth(120)
    rk_form.addRow("Background zoom:", window.rk_bg_zoom)

    rk_bg_offset_row = QtWidgets.QHBoxLayout()
    window.rk_bg_x = QtWidgets.QSpinBox()
    window.rk_bg_x.setRange(-4000, 4000)
    window.rk_bg_x.setSingleStep(10)
    window.rk_bg_x.setFixedWidth(110)
    window.rk_bg_y = QtWidgets.QSpinBox()
    window.rk_bg_y.setRange(-4000, 4000)
    window.rk_bg_y.setSingleStep(10)
    window.rk_bg_y.setFixedWidth(110)
    rk_bg_offset_row.addWidget(QtWidgets.QLabel("X"))
    rk_bg_offset_row.addWidget(window.rk_bg_x)
    rk_bg_offset_row.addSpacing(10)
    rk_bg_offset_row.addWidget(QtWidgets.QLabel("Y"))
    rk_bg_offset_row.addWidget(window.rk_bg_y)
    rk_bg_offset_row.addStretch()
    rk_form.addRow("Background offset:", rk_bg_offset_row)

    rk_form.addRow(_section_label("Typography"))
    window.rk_name_font = QtWidgets.QComboBox()
    window.rk_name_font.setEditable(True)
    window.rk_name_font.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
    rk_form.addRow("Name font:", window.rk_name_font)

    window.rk_info_font = QtWidgets.QComboBox()
    window.rk_info_font.setEditable(True)
    window.rk_info_font.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
    rk_form.addRow("Info font:", window.rk_info_font)

    window.rk_name_size = QtWidgets.QSpinBox()
    window.rk_name_size.setRange(8, 200)
    window.rk_name_size.setValue(60)
    window.rk_name_size.setFixedWidth(120)
    rk_form.addRow("Name size:", window.rk_name_size)

    window.rk_info_size = QtWidgets.QSpinBox()
    window.rk_info_size.setRange(8, 120)
    window.rk_info_size.setValue(40)
    window.rk_info_size.setFixedWidth(120)
    rk_form.addRow("Info size:", window.rk_info_size)

    window.rk_name_color = QtWidgets.QLineEdit()
    window.rk_name_color.setPlaceholderText("#FFFFFF")
    window.rk_name_color_pick = QtWidgets.QPushButton("Pick...")
    window.rk_name_color_pick.setFixedWidth(72)
    rk_name_color_row = QtWidgets.QHBoxLayout()
    rk_name_color_row.addWidget(window.rk_name_color, 1)
    rk_name_color_row.addWidget(window.rk_name_color_pick, 0)
    rk_form.addRow("Name color:", rk_name_color_row)

    window.rk_info_color = QtWidgets.QLineEdit()
    window.rk_info_color.setPlaceholderText("#C8C8C8")
    window.rk_info_color_pick = QtWidgets.QPushButton("Pick...")
    window.rk_info_color_pick.setFixedWidth(72)
    rk_info_color_row = QtWidgets.QHBoxLayout()
    rk_info_color_row.addWidget(window.rk_info_color, 1)
    rk_info_color_row.addWidget(window.rk_info_color_pick, 0)
    rk_form.addRow("Info color:", rk_info_color_row)

    rk_text_pos_row = QtWidgets.QHBoxLayout()
    window.rk_text_x = QtWidgets.QSpinBox()
    window.rk_text_x.setRange(-2000, 2000)
    window.rk_text_x.setSingleStep(5)
    window.rk_text_x.setFixedWidth(110)
    window.rk_text_y = QtWidgets.QSpinBox()
    window.rk_text_y.setRange(-2000, 2000)
    window.rk_text_y.setSingleStep(5)
    window.rk_text_y.setFixedWidth(110)
    rk_text_pos_row.addWidget(QtWidgets.QLabel("X"))
    rk_text_pos_row.addWidget(window.rk_text_x)
    rk_text_pos_row.addSpacing(10)
    rk_text_pos_row.addWidget(QtWidgets.QLabel("Y"))
    rk_text_pos_row.addWidget(window.rk_text_y)
    rk_text_pos_row.addStretch()
    rk_form.addRow("Text offset:", rk_text_pos_row)
    rk_controls_layout.addLayout(rk_form)

    info = QtWidgets.QLabel("Choose a background PNG to preview the rank. Use Save + Reload to apply to the bot.")
    info.setWordWrap(True)
    info.setStyleSheet("color:#9aa0a6; font-size:11px; margin-top:8px;")
    rk_controls_layout.addWidget(info)
    rk_controls_layout.addStretch()

    rk_scroll = QtWidgets.QScrollArea()
    rk_scroll.setWidgetResizable(True)
    rk_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
    rk_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
    rk_scroll.setContentsMargins(0, 0, 10, 0)
    rk_scroll.setWidget(rk_controls_w)
    rk_right.addWidget(rk_scroll, 1)

    rk_buttons = QtWidgets.QHBoxLayout()
    window.rk_refresh = QtWidgets.QPushButton("Refresh Rank")
    window.rk_save = QtWidgets.QPushButton("Save")
    window.rk_save_reload = QtWidgets.QPushButton("Save + Reload")
    for _btn in (window.rk_refresh, window.rk_save, window.rk_save_reload):
        try:
            _btn.setMinimumWidth(_btn.sizeHint().width() + 18)
            _btn.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        except Exception:
            pass
    rk_buttons.addStretch()
    rk_buttons.addWidget(window.rk_refresh)
    rk_buttons.addWidget(window.rk_save)
    rk_buttons.addWidget(window.rk_save_reload)
    rk_right.addLayout(rk_buttons)

    rk_main.addLayout(rk_left, 0)
    rk_main.addLayout(rk_right, 1)
    rank_layout.addLayout(rk_main)

    tabs.addTab(rank_w, "Rankcard")

    leveling_w = QtWidgets.QWidget()
    leveling_layout = QtWidgets.QVBoxLayout(leveling_w)
    leveling_layout.setContentsMargins(8, 8, 10, 8)
    leveling_layout.setSpacing(10)

    lv_scroll = QtWidgets.QScrollArea()
    lv_scroll.setWidgetResizable(True)
    lv_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
    lv_content = QtWidgets.QWidget()
    lv_content_layout = QtWidgets.QVBoxLayout(lv_content)

    lv_form = QtWidgets.QFormLayout()
    lv_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
    lv_form.setFormAlignment(QtCore.Qt.AlignTop | QtCore.Qt.AlignLeft)
    lv_form.setLabelAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
    lv_form.setHorizontalSpacing(10)
    lv_form.setVerticalSpacing(8)
    lv_form.setContentsMargins(0, 0, 18, 0)

    lv_form.addRow(_section_label("XP Settings"))
    window.lv_xp_per_message = QtWidgets.QSpinBox()
    window.lv_xp_per_message.setRange(1, 10000)
    window.lv_xp_per_message.setValue(15)
    window.lv_xp_per_message.setFixedWidth(140)
    lv_form.addRow("XP per message:", window.lv_xp_per_message)

    window.lv_voice_xp_per_minute = QtWidgets.QSpinBox()
    window.lv_voice_xp_per_minute.setRange(1, 10000)
    window.lv_voice_xp_per_minute.setValue(10)
    window.lv_voice_xp_per_minute.setFixedWidth(140)
    lv_form.addRow("Voice XP per minute:", window.lv_voice_xp_per_minute)

    window.lv_message_cooldown = QtWidgets.QSpinBox()
    window.lv_message_cooldown.setRange(0, 3600)
    window.lv_message_cooldown.setValue(30)
    window.lv_message_cooldown.setSuffix(" s")
    window.lv_message_cooldown.setFixedWidth(140)
    lv_form.addRow("Message cooldown:", window.lv_message_cooldown)

    lv_form.addRow(_section_label("Messages"))
    window.lv_levelup_msg = QtWidgets.QPlainTextEdit()
    window.lv_levelup_msg.setMinimumHeight(96)
    window.lv_levelup_msg.setMaximumHeight(170)
    window.lv_levelup_msg.setPlaceholderText(
        "Use {member_mention}, {member_name}, {member_display_name}, {member_id}, {guild_name}, {level}"
    )
    window.lv_emoji_win = QtWidgets.QLineEdit()
    window.lv_emoji_win.setPlaceholderText("Leading emoji ID or <:name:id>")
    window.lv_emoji_win_picker_btn = QtWidgets.QPushButton("Pick...")
    window.lv_emoji_win_picker_btn.setFixedWidth(72)
    lv_leading_row = QtWidgets.QHBoxLayout()
    lv_leading_row.addWidget(window.lv_emoji_win, 1)
    lv_leading_row.addWidget(window.lv_emoji_win_picker_btn, 0)
    lv_form.addRow("Leading emoji ID/tag:", lv_leading_row)

    window.lv_emoji_heart = QtWidgets.QLineEdit()
    window.lv_emoji_heart.setPlaceholderText("Trailing emoji ID or <:name:id>")
    window.lv_emoji_heart_picker_btn = QtWidgets.QPushButton("Pick...")
    window.lv_emoji_heart_picker_btn.setFixedWidth(72)
    lv_trailing_row = QtWidgets.QHBoxLayout()
    lv_trailing_row.addWidget(window.lv_emoji_heart, 1)
    lv_trailing_row.addWidget(window.lv_emoji_heart_picker_btn, 0)
    lv_form.addRow("Trailing emoji ID/tag:", lv_trailing_row)
    lv_form.addRow("Level-up message:", window.lv_levelup_msg)

    window.lv_levelup_emoji_picker_btn = QtWidgets.QPushButton("Insert server emoji into level-up message...")
    lv_form.addRow("", window.lv_levelup_emoji_picker_btn)

    window.lv_ph_member_mention = QtWidgets.QPushButton("{member_mention}")
    window.lv_ph_member_name = QtWidgets.QPushButton("{member_name}")
    window.lv_ph_display_name = QtWidgets.QPushButton("{member_display_name}")
    window.lv_ph_member_id = QtWidgets.QPushButton("{member_id}")
    window.lv_ph_guild_name = QtWidgets.QPushButton("{guild_name}")
    window.lv_ph_level = QtWidgets.QPushButton("{level}")
    window.lv_ph_leading_emoji = QtWidgets.QPushButton("{leading_emoji}")
    window.lv_ph_trailing_emoji = QtWidgets.QPushButton("{trailing_emoji}")

    lv_ph_widget = QtWidgets.QWidget()
    lv_ph_grid = QtWidgets.QGridLayout(lv_ph_widget)
    lv_ph_grid.setContentsMargins(0, 0, 0, 0)
    lv_ph_grid.setHorizontalSpacing(8)
    lv_ph_grid.setVerticalSpacing(8)
    lv_ph_grid.addWidget(window.lv_ph_member_mention, 0, 0)
    lv_ph_grid.addWidget(window.lv_ph_member_name, 0, 1)
    lv_ph_grid.addWidget(window.lv_ph_display_name, 0, 2)
    lv_ph_grid.addWidget(window.lv_ph_member_id, 1, 0)
    lv_ph_grid.addWidget(window.lv_ph_guild_name, 1, 1)
    lv_ph_grid.addWidget(window.lv_ph_level, 1, 2)
    lv_ph_grid.addWidget(window.lv_ph_leading_emoji, 2, 0)
    lv_ph_grid.addWidget(window.lv_ph_trailing_emoji, 2, 1)
    lv_form.addRow("Level placeholders:", lv_ph_widget)

    window.lv_achievement_msg = QtWidgets.QPlainTextEdit()
    window.lv_achievement_msg.setMinimumHeight(86)
    window.lv_achievement_msg.setMaximumHeight(150)
    window.lv_achievement_msg.setPlaceholderText(
        "Use {member_mention}, {member_name}, {member_display_name}, {member_id}, {guild_name}, {achievement_name}"
    )
    lv_form.addRow("Achievement message:", window.lv_achievement_msg)

    window.lv_achievement_emoji_picker_btn = QtWidgets.QPushButton("Insert server emoji into achievement message...")
    lv_form.addRow("", window.lv_achievement_emoji_picker_btn)

    window.av_ph_member_mention = QtWidgets.QPushButton("{member_mention}")
    window.av_ph_member_name = QtWidgets.QPushButton("{member_name}")
    window.av_ph_display_name = QtWidgets.QPushButton("{member_display_name}")
    window.av_ph_member_id = QtWidgets.QPushButton("{member_id}")
    window.av_ph_guild_name = QtWidgets.QPushButton("{guild_name}")
    window.av_ph_achievement_name = QtWidgets.QPushButton("{achievement_name}")
    for _btn in (
        window.lv_ph_member_mention,
        window.lv_ph_member_name,
        window.lv_ph_display_name,
        window.lv_ph_member_id,
        window.lv_ph_guild_name,
        window.lv_ph_level,
        window.lv_ph_leading_emoji,
        window.lv_ph_trailing_emoji,
        window.av_ph_member_mention,
        window.av_ph_member_name,
        window.av_ph_display_name,
        window.av_ph_member_id,
        window.av_ph_guild_name,
        window.av_ph_achievement_name,
    ):
        try:
            _btn.setMinimumHeight(34)
        except Exception:
            pass

    av_ph_widget = QtWidgets.QWidget()
    av_ph_grid = QtWidgets.QGridLayout(av_ph_widget)
    av_ph_grid.setContentsMargins(0, 0, 0, 0)
    av_ph_grid.setHorizontalSpacing(8)
    av_ph_grid.setVerticalSpacing(8)
    av_ph_grid.addWidget(window.av_ph_member_mention, 0, 0)
    av_ph_grid.addWidget(window.av_ph_member_name, 0, 1)
    av_ph_grid.addWidget(window.av_ph_display_name, 0, 2)
    av_ph_grid.addWidget(window.av_ph_member_id, 1, 0)
    av_ph_grid.addWidget(window.av_ph_guild_name, 1, 1)
    av_ph_grid.addWidget(window.av_ph_achievement_name, 1, 2)
    lv_form.addRow("Achievement placeholders:", av_ph_widget)

    lv_form.addRow(_section_label("Rewards & Achievements"))
    window.lv_rewards_table = QtWidgets.QTableWidget(0, 2)
    window.lv_rewards_table.setHorizontalHeaderLabels(["Level", "Role name"])
    window.lv_rewards_table.verticalHeader().setVisible(False)
    window.lv_rewards_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    window.lv_rewards_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
    window.lv_rewards_table.horizontalHeader().setStretchLastSection(True)
    window.lv_rewards_table.setSortingEnabled(True)
    window.lv_rewards_table.setMinimumHeight(170)
    lv_form.addRow("Level rewards:", window.lv_rewards_table)

    rewards_btns = QtWidgets.QHBoxLayout()
    window.lv_rewards_add_btn = QtWidgets.QPushButton("Add reward")
    window.lv_rewards_remove_btn = QtWidgets.QPushButton("Remove selected")
    rewards_btns.addWidget(window.lv_rewards_add_btn)
    rewards_btns.addWidget(window.lv_rewards_remove_btn)
    rewards_btns.addStretch()
    lv_form.addRow("", rewards_btns)

    window.lv_achievements_table = QtWidgets.QTableWidget(0, 4)
    window.lv_achievements_table.setHorizontalHeaderLabels(["Achievement", "Type", "Value", "Image (URL/Path)"])
    window.lv_achievements_table.verticalHeader().setVisible(False)
    window.lv_achievements_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    window.lv_achievements_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
    window.lv_achievements_table.horizontalHeader().setStretchLastSection(True)
    window.lv_achievements_table.setSortingEnabled(True)
    window.lv_achievements_table.setMinimumHeight(220)
    lv_form.addRow("Achievements:", window.lv_achievements_table)

    ach_btns = QtWidgets.QHBoxLayout()
    window.lv_achievements_add_btn = QtWidgets.QPushButton("Add achievement")
    window.lv_achievements_remove_btn = QtWidgets.QPushButton("Remove selected")
    window.lv_achievements_choose_image_btn = QtWidgets.QPushButton("Choose image...")
    ach_btns.addWidget(window.lv_achievements_add_btn)
    ach_btns.addWidget(window.lv_achievements_remove_btn)
    ach_btns.addWidget(window.lv_achievements_choose_image_btn)
    ach_btns.addStretch()
    lv_form.addRow("", ach_btns)

    req_hint = QtWidgets.QLabel("Type supports: messages, voice_time, level, xp • Image supports URL or local path")
    req_hint.setStyleSheet("color:#9aa0a6;")
    lv_form.addRow("", req_hint)

    lv_content_layout.addLayout(lv_form)
    lv_content_layout.addStretch()
    lv_scroll.setWidget(lv_content)
    leveling_layout.addWidget(lv_scroll, 1)

    lv_buttons = QtWidgets.QHBoxLayout()
    window.lv_save = QtWidgets.QPushButton("Save")
    window.lv_save_reload = QtWidgets.QPushButton("Save + Reload")
    for _btn in (window.lv_save, window.lv_save_reload):
        try:
            _btn.setMinimumWidth(_btn.sizeHint().width() + 18)
            _btn.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        except Exception:
            pass
    lv_buttons.addStretch()
    lv_buttons.addWidget(window.lv_save)
    lv_buttons.addWidget(window.lv_save_reload)
    leveling_layout.addLayout(lv_buttons)

    tabs.addTab(leveling_w, "Leveling")

    birthdays_w = QtWidgets.QWidget()
    birthdays_layout = QtWidgets.QVBoxLayout(birthdays_w)
    birthdays_layout.setContentsMargins(8, 8, 10, 8)
    birthdays_layout.setSpacing(10)

    bd_scroll = QtWidgets.QScrollArea()
    bd_scroll.setWidgetResizable(True)
    bd_content = QtWidgets.QWidget()
    bd_content_layout = QtWidgets.QVBoxLayout(bd_content)
    bd_form = QtWidgets.QFormLayout()
    bd_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
    bd_form.setFormAlignment(QtCore.Qt.AlignTop | QtCore.Qt.AlignLeft)
    bd_form.setLabelAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
    bd_form.setHorizontalSpacing(10)
    bd_form.setVerticalSpacing(8)

    window.bd_embed_title = QtWidgets.QLineEdit()
    window.bd_embed_title.setPlaceholderText("🎂 Birthday")
    bd_form.addRow("Embed title:", window.bd_embed_title)

    window.bd_embed_description = QtWidgets.QPlainTextEdit()
    window.bd_embed_description.setMinimumHeight(110)
    window.bd_embed_description.setPlaceholderText("🎉 Today is {mention}'s birthday!")
    bd_form.addRow("Embed message:", window.bd_embed_description)

    ph_widget = QtWidgets.QWidget()
    ph_layout = QtWidgets.QGridLayout(ph_widget)
    ph_layout.setContentsMargins(0, 0, 0, 0)
    ph_layout.setHorizontalSpacing(8)
    ph_layout.setVerticalSpacing(8)
    window.bd_ph_mention = QtWidgets.QPushButton("{mention}")
    window.bd_ph_user_name = QtWidgets.QPushButton("{user_name}")
    window.bd_ph_display_name = QtWidgets.QPushButton("{display_name}")
    window.bd_ph_user_id = QtWidgets.QPushButton("{user_id}")
    window.bd_ph_date = QtWidgets.QPushButton("{date}")
    for _btn in (
        window.bd_ph_mention,
        window.bd_ph_user_name,
        window.bd_ph_display_name,
        window.bd_ph_user_id,
        window.bd_ph_date,
    ):
        try:
            _btn.setMinimumHeight(34)
        except Exception:
            pass
    ph_layout.addWidget(window.bd_ph_mention, 0, 0)
    ph_layout.addWidget(window.bd_ph_user_name, 0, 1)
    ph_layout.addWidget(window.bd_ph_display_name, 0, 2)
    ph_layout.addWidget(window.bd_ph_user_id, 1, 0)
    ph_layout.addWidget(window.bd_ph_date, 1, 1)
    bd_form.addRow("Placeholders:", ph_widget)

    window.bd_emoji_picker_btn = QtWidgets.QPushButton("Server Emoji Picker...")
    bd_form.addRow("Server emojis:", window.bd_emoji_picker_btn)

    window.bd_embed_footer = QtWidgets.QLineEdit()
    window.bd_embed_footer.setPlaceholderText("Optional footer")
    bd_form.addRow("Embed footer:", window.bd_embed_footer)

    window.bd_embed_color = QtWidgets.QLineEdit()
    window.bd_embed_color.setPlaceholderText("#F1C40F")
    window.bd_embed_color_pick = QtWidgets.QPushButton("Pick...")
    window.bd_embed_color_pick.setFixedWidth(72)
    bd_color_row = QtWidgets.QHBoxLayout()
    bd_color_row.addWidget(window.bd_embed_color, 1)
    bd_color_row.addWidget(window.bd_embed_color_pick, 0)
    bd_form.addRow("Embed color:", bd_color_row)

    bd_hint = QtWidgets.QLabel("Message is sent as embed once per birthday/day.")
    bd_hint.setStyleSheet("color:#9aa0a6;")
    bd_form.addRow("", bd_hint)

    bd_content_layout.addLayout(bd_form)
    bd_content_layout.addStretch()
    bd_scroll.setWidget(bd_content)
    birthdays_layout.addWidget(bd_scroll, 1)

    bd_buttons = QtWidgets.QHBoxLayout()
    window.bd_save = QtWidgets.QPushButton("Save")
    window.bd_save_reload = QtWidgets.QPushButton("Save + Reload")
    for _btn in (window.bd_save, window.bd_save_reload):
        try:
            _btn.setMinimumWidth(_btn.sizeHint().width() + 18)
            _btn.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        except Exception:
            pass
    bd_buttons.addStretch()
    bd_buttons.addWidget(window.bd_save)
    bd_buttons.addWidget(window.bd_save_reload)
    birthdays_layout.addLayout(bd_buttons)

    tabs.addTab(birthdays_w, "Birthdays")

    window.rk_refresh.clicked.connect(window.on_refresh_rankpreview)
    window.rk_bg_browse.clicked.connect(window._choose_rank_bg)
    window.rk_name_color_pick.clicked.connect(lambda: window._pick_color(window.rk_name_color, "Choose rank name color"))
    window.rk_info_color_pick.clicked.connect(lambda: window._pick_color(window.rk_info_color, "Choose rank info color"))
    window.lv_ph_member_mention.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{member_mention}'))
    window.lv_ph_member_name.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{member_name}'))
    window.lv_ph_display_name.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{member_display_name}'))
    window.lv_ph_member_id.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{member_id}'))
    window.lv_ph_guild_name.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{guild_name}'))
    window.lv_ph_level.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{level}'))
    window.lv_ph_leading_emoji.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{leading_emoji}'))
    window.lv_ph_trailing_emoji.clicked.connect(lambda: window._insert_placeholder_into(window.lv_levelup_msg, '{trailing_emoji}'))
    window.av_ph_member_mention.clicked.connect(lambda: window._insert_placeholder_into(window.lv_achievement_msg, '{member_mention}'))
    window.av_ph_member_name.clicked.connect(lambda: window._insert_placeholder_into(window.lv_achievement_msg, '{member_name}'))
    window.av_ph_display_name.clicked.connect(lambda: window._insert_placeholder_into(window.lv_achievement_msg, '{member_display_name}'))
    window.av_ph_member_id.clicked.connect(lambda: window._insert_placeholder_into(window.lv_achievement_msg, '{member_id}'))
    window.av_ph_guild_name.clicked.connect(lambda: window._insert_placeholder_into(window.lv_achievement_msg, '{guild_name}'))
    window.av_ph_achievement_name.clicked.connect(lambda: window._insert_placeholder_into(window.lv_achievement_msg, '{achievement_name}'))
    window.lv_rewards_add_btn.clicked.connect(window.on_leveling_add_reward_row)
    window.lv_rewards_remove_btn.clicked.connect(window.on_leveling_remove_reward_row)
    window.lv_achievements_add_btn.clicked.connect(window.on_leveling_add_achievement_row)
    window.lv_achievements_remove_btn.clicked.connect(window.on_leveling_remove_achievement_row)
    window.lv_achievements_choose_image_btn.clicked.connect(window.on_leveling_choose_achievement_image)
    window.lv_emoji_win_picker_btn.clicked.connect(window.on_open_leveling_leading_emoji_picker)
    window.lv_emoji_heart_picker_btn.clicked.connect(window.on_open_leveling_trailing_emoji_picker)
    window.lv_levelup_emoji_picker_btn.clicked.connect(window.on_open_leveling_levelup_emoji_picker)
    window.lv_achievement_emoji_picker_btn.clicked.connect(window.on_open_leveling_achievement_emoji_picker)
    window.lv_save.clicked.connect(lambda: window._save_leveling_settings(reload_after=False))
    window.lv_save_reload.clicked.connect(lambda: window._save_leveling_settings(reload_after=True))
    window.bd_ph_mention.clicked.connect(lambda: window._insert_placeholder_into(window.bd_embed_description, '{mention}'))
    window.bd_ph_user_name.clicked.connect(lambda: window._insert_placeholder_into(window.bd_embed_description, '{user_name}'))
    window.bd_ph_display_name.clicked.connect(lambda: window._insert_placeholder_into(window.bd_embed_description, '{display_name}'))
    window.bd_ph_user_id.clicked.connect(lambda: window._insert_placeholder_into(window.bd_embed_description, '{user_id}'))
    window.bd_ph_date.clicked.connect(lambda: window._insert_placeholder_into(window.bd_embed_description, '{date}'))
    window.bd_emoji_picker_btn.clicked.connect(window.on_open_birthday_emoji_picker)
    window.bd_embed_color_pick.clicked.connect(lambda: window._pick_color(window.bd_embed_color, "Choose birthday embed color"))
    window.bd_save.clicked.connect(lambda: window._save_birthday_settings(reload_after=False))
    window.bd_save_reload.clicked.connect(lambda: window._save_birthday_settings(reload_after=True))
    window.rk_save.clicked.connect(lambda: window._save_rank_preview(reload_after=False))
    window.rk_save_reload.clicked.connect(lambda: window._save_rank_preview(reload_after=True))

    window.pv_banner_browse.clicked.connect(window._choose_banner)
    window.pv_emoji_picker_btn.clicked.connect(window.on_open_welcome_emoji_picker)
    window.pv_title_color_pick.clicked.connect(lambda: window._pick_color(window.pv_title_color, "Choose title color"))
    window.pv_user_color_pick.clicked.connect(lambda: window._pick_color(window.pv_user_color, "Choose username color"))
    window.pv_refresh.clicked.connect(window.on_refresh_preview)
    window.pv_save.clicked.connect(lambda: window._save_preview(reload_after=False))
    window.pv_save_reload.clicked.connect(lambda: window._save_preview(reload_after=True))

    window._preview_debounce = QtCore.QTimer(window)
    window._preview_debounce.setSingleShot(True)
    window._preview_debounce.setInterval(250)
    window._preview_debounce.timeout.connect(window._apply_live_preview)

    window.pv_name.textChanged.connect(lambda: window._preview_debounce.start())
    window.pv_banner_path.textChanged.connect(lambda: window._preview_debounce.start())
    window.pv_message.textChanged.connect(lambda: window._preview_debounce.start())
    window.pv_bg_mode.currentIndexChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_bg_zoom.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_bg_x.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_bg_y.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_title.textChanged.connect(lambda: window._preview_debounce.start())
    window.pv_title_font.currentTextChanged.connect(lambda _t: window._preview_debounce.start())
    window.pv_user_font.currentTextChanged.connect(lambda _t: window._preview_debounce.start())
    window.pv_title_size.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_user_size.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_title_color.textChanged.connect(lambda: window._preview_debounce.start())
    window.pv_user_color.textChanged.connect(lambda: window._preview_debounce.start())
    window.pv_title_x.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_title_y.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_user_x.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_user_y.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_text_x.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_text_y.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_avatar_x.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_avatar_y.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.pv_name.textChanged.connect(window._mark_preview_dirty)
    window.pv_banner_path.textChanged.connect(window._mark_preview_dirty)
    window.pv_message.textChanged.connect(window._mark_preview_dirty)
    window.pv_bg_mode.currentIndexChanged.connect(window._mark_preview_dirty)
    window.pv_bg_zoom.valueChanged.connect(window._mark_preview_dirty)
    window.pv_bg_x.valueChanged.connect(window._mark_preview_dirty)
    window.pv_bg_y.valueChanged.connect(window._mark_preview_dirty)
    window.pv_title.textChanged.connect(window._mark_preview_dirty)
    window.pv_title_font.currentTextChanged.connect(window._mark_preview_dirty)
    window.pv_user_font.currentTextChanged.connect(window._mark_preview_dirty)
    window.pv_title_size.valueChanged.connect(window._mark_preview_dirty)
    window.pv_user_size.valueChanged.connect(window._mark_preview_dirty)
    window.pv_title_color.textChanged.connect(window._mark_preview_dirty)
    window.pv_user_color.textChanged.connect(window._mark_preview_dirty)
    window.pv_title_x.valueChanged.connect(window._mark_preview_dirty)
    window.pv_title_y.valueChanged.connect(window._mark_preview_dirty)
    window.pv_user_x.valueChanged.connect(window._mark_preview_dirty)
    window.pv_user_y.valueChanged.connect(window._mark_preview_dirty)
    window.pv_text_x.valueChanged.connect(window._mark_preview_dirty)
    window.pv_text_y.valueChanged.connect(window._mark_preview_dirty)
    window.pv_avatar_x.valueChanged.connect(window._mark_preview_dirty)
    window.pv_avatar_y.valueChanged.connect(window._mark_preview_dirty)
    window.rk_name.textChanged.connect(lambda: window._preview_debounce.start())
    window.rk_bg_path.textChanged.connect(lambda: window._preview_debounce.start())
    window.rk_bg_mode.currentIndexChanged.connect(lambda _v: window._preview_debounce.start())
    window.rk_bg_zoom.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.rk_bg_x.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.rk_bg_y.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.rk_name_font.currentTextChanged.connect(lambda _t: window._preview_debounce.start())
    window.rk_info_font.currentTextChanged.connect(lambda _t: window._preview_debounce.start())
    window.rk_name_size.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.rk_info_size.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.rk_name_color.textChanged.connect(lambda: window._preview_debounce.start())
    window.rk_info_color.textChanged.connect(lambda: window._preview_debounce.start())
    window.rk_text_x.valueChanged.connect(lambda _v: window._preview_debounce.start())
    window.rk_text_y.valueChanged.connect(lambda _v: window._preview_debounce.start())
